### ISSUE TITLE
When I right click and paste the credit card number it is not formatted

### ISSUE THREAD

**Issue by nikolodien** [CardJs/CardJs#26] opened 2017-06-07 01:37 UTC
Copy any number, and right-click + paste in the input field. 

The card number is left unformatted

**Comment by pandymic** [comment] 2017-06-09 21:28
Just tried and I can confirm this behavior as well.

Seems like a perfect use-case for the `onpaste` event that's inherently available with the major browsers. Solution is as simple as causing the text-field to poll itself for changes when a paste is detected. I'll give it a try and report back!

**Comment by colin-stannard** [comment] 2017-07-05 22:43
Fixed as of v1.0.14 (see 35641cb)

The solution for this is slightly hacky but appears to work reliably across browsers. Uses the 'paste' event trigger with a short timeout since there is no 'after-paste' event available. Without the timeout the event triggers preemptively and does not format the pasted text.

The 'change' event is not suitable for handling pastes since it doesn't trigger until the user clicks off of the input box.

This is implemented for the card number, expiry date and cvc.

**Closed as completed by colin-stannard** 2017-07-05 22:43 UTC
